name: anime
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  build_runner: ^2.4.15
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.12.0
  flutter_svg: ^2.0.16
  google_nav_bar: ^5.0.7
  iconsax: ^0.0.8
  iconsax_flutter: ^1.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 800
